### ISSUE TITLE
got error for multi resolution target domain

### ISSUE THREAD

**Issue by nimaone** [lhoyer/MIC#10]
hi thank you for your amazing work 👍 
I got error when I was training the model on my custom dataset with   "MIC_ON: True" :
my custom dataset has multi resolution images and when i was training i got error in a file: "MIC/det/maskrcnn_benchmark/structures/boxlist_ops.py" 
at line "113,114" ---->
 113: size = bboxes[0].size
 114: assert all(bbox.size == size for bbox in bboxes)

i just print the "size" and "bbox.size" and look like there is a mismatch here!
size (1088, 800)
(1088, 800)
(1066, 800)

do you have any idea how can I resolve this problem??

the full error here:

Traceback (most recent call last):
  File "tools/train_net.py", line 270, in <module>
    main()
  File "tools/train_net.py", line 263, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 114, in train
    do_mask_da_train(
  File "/content/MIC/det/maskrcnn_benchmark/engine/trainer.py", line 246, in do_mask_da_train
    masked_loss_dict = model(masked_images, masked_taget, use_pseudo_labeling_weight=cfg.MODEL.PSEUDO_LABEL_WEIGHT, with_DA_ON=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/MIC/det/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 54, in forward
    proposals, proposal_losses = self.rpn(images, features, targets, use_pseudo_labeling_weight=use_pseudo_labeling_weight)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/MIC/det/maskrcnn_benchmark/modeling/rpn/rpn.py", line 100, in forward
    return self._forward_train(anchors, objectness, rpn_box_regression, targets, use_pseudo_labeling_weight)
  File "/content/MIC/det/maskrcnn_benchmark/modeling/rpn/rpn.py", line 115, in _forward_train
    boxes = self.box_selector_train(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/MIC/det/maskrcnn_benchmark/modeling/rpn/inference.py", line 148, in forward
    boxlists = self.add_gt_proposals(boxlists, targets)
  File "/content/MIC/det/maskrcnn_benchmark/modeling/rpn/inference.py", line 67, in add_gt_proposals
    proposals = [
  File "/content/MIC/det/maskrcnn_benchmark/modeling/rpn/inference.py", line 68, in <listcomp>
    cat_boxlist((proposal, gt_box))
  File "/content/MIC/det/maskrcnn_benchmark/structures/boxlist_ops.py", line 121, in cat_boxlist
    assert all(bbox.size == size for bbox in bboxes)
AssertionError

by the way there is no issue to train model with  "MIC_ON: False"

**Comment by krumo** [comment]
Hi, I find this error comes from the inconsistent image size for **masked_images** and **target_images** in https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/det/maskrcnn_benchmark/engine/trainer.py#L244. Here **target_images** is an ImageList structure, while **masked_images** is just a PyTorch Tensor. 

Because in config  https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/det/configs/da_faster_rcnn/e2e_da_faster_rcnn_R_50_FPN_masking_cs.yaml#L47 SIZE_DIVISIBILITY is set to 32. The image_size in **target_images** might be different from the real tensor's size.


For the solution, you can replace [line244](https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/det/maskrcnn_benchmark/engine/trainer.py#L244) with the following code to ensure the **masked_images** has the same image size as **target_images**
```
from maskrcnn_benchmark.structures.image_list import ImageList
masked_images = ImageList(masked_target_images[pseudo_masks], target_images.image_sizes)
```

Thanks for your reporting! I will commit this modification to the repository soon.

**Comment by nimaone** [comment]
> Hi, I find this error comes from the inconsistent image size for **masked_images** and **target_images** in
> 
> https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/det/maskrcnn_benchmark/engine/trainer.py#L244
> 
> . Here **target_images** is an ImageList structure, while **masked_images** is just a PyTorch Tensor.
> Because in config
> 
> https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/det/configs/da_faster_rcnn/e2e_da_faster_rcnn_R_50_FPN_masking_cs.yaml#L47
> 
> SIZE_DIVISIBILITY is set to 32 and tensors will be padded to a size which is divisible by 32. Thus, the image_size in **target_images** might be different from the real tensor's size. (In your example, 1088 is divisible by 32 but 1066 is not)
> For the solution, you can replace [line244](https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/det/maskrcnn_benchmark/engine/trainer.py#L244) with the following code to ensure the **masked_images** has the same image size as **target_images**
> 
> ```
> from maskrcnn_benchmark.structures.image_list import ImageList
> masked_images = ImageList(masked_target_images[pseudo_masks], target_images.image_sizes)
> ```
> 
> Thanks for your reporting! I will commit this modification to the repository soon.

Thank you very much for your quick reply and solving my problem, sorry for not being able to reply these two weeks.
As you said, I changed that part of the code and everything was fixed
Thank you again for making your work open source 👌👌
