### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by amateurj1** [lhoyer/MIC#12]
Hi,your work is awesome!So I'm eager to know the implementation of MIC. But I have several problems as follows.
     1. How can I get the config of model Adversarial[86] which in Table1. ?  Can you provide it ?   Adversaria[86]  is a simple UDA model.  By debugging the code of this model, I can easily understand the idea and implementation details of MIC .
     2. This code runs on the basis of mmcv. I haven't touched the mmcv framework. It is difficult for me to understand and debug the code, and to clearly understand the implementation details of MIC. I found that others also mentioned in the issue that mmcv is difficult to debug.Can you provide concise code about MIC? I believe this will be beneficial to the promotion and use of MIC.
     I'm looking forward to your early reply! Thank you very much!

**Comment by lhoyer** [comment]
Thank you for your interest in our work! 

1. You can generate the configs of Table 1 using `python run_experiments.py --exp 1`. Further details are provided in the README.md. Please, also refer to https://github.com/lhoyer/MIC/blob/629ba8e7d6e0246559f643a05c24ad3808dd6a3a/seg/experiments.py#L417.
2. The REAMDE.md (https://github.com/lhoyer/MIC/tree/master/seg#framework-structure) provides some pointers where the relevant code is located in the framework. In particular, the MIC code is located in this file: https://github.com/lhoyer/MIC/blob/master/seg/mmseg/models/uda/masking_consistency_module.py

**Comment by amateurj1** [comment]
Thanks!Awesome work!
