### ISSUE TITLE
questions about mask 

### ISSUE THREAD

**Issue by chenyang126** [lhoyer/MIC#15]
Hi!
Your work is excellent! But in your paper 4.5. In-Depth Analysis of MIC, you say "Therefore, we also apply MIC to the source domain, in addition to the default target domain, for clear-to-adverse-weather and day-to-nighttime adaptation", however, in your config, you use mask_mode: separatetrgaug, did you use mask module in cityscapes2acdc in soure domain?

**Comment by lhoyer** [comment]
Thank you for your interest in our work! The standalone config https://github.com/lhoyer/MIC/blob/master/seg/configs/mic/gtaHR2csHR_mic_hrda.py is specific to GTA->Cityscapes. For the other datasets, please refer to the automatic experiment config generation in https://github.com/lhoyer/MIC/blob/master/seg/experiments.py#L394. Here, you can see that `mask_mode` is `separate` (both source and target domain images) for Cityscapes->ACDC. You can also see this in the accompanying config of the checkpoint for Cityscapes->ACDC as provided in https://github.com/lhoyer/MIC/tree/master/seg#checkpoints.

**Comment by chenyang126** [comment]
Thanks for your help!
