### ISSUE TITLE
A question about DACS implementation

### ISSUE THREAD

**Issue by EEAIC** [lhoyer/MIC#18]
Dear @lhoyer,

While I'm studying your research in detail, I have a question about your code implementation.

In DACS, the algorithm selects half of the classes for a given image.

However, your implementation selects half of the classes for all given images in batch.

https://github.com/lhoyer/MIC/blob/a655163f2bb3e4535f1eccacf74d2ea8e52d7cb0/seg/mmseg/models/utils/dacs_transforms.py#L93

I think `torch.unique(labels)` should be `torch.unique(label)`.

Although my understanding of DACS could be incorrect, could you give me any advice about this?

Best regards,
Jeongkee

**Comment by lhoyer** [comment]
Dear Jeongkee,

You are right. This is indeed different from the DACS implementation as discussed in https://github.com/lhoyer/DAFormer/issues/19. We later also ran an experiment with the original DACS variant, which confirmed that this difference does not affect the final performance. We kept using the DAFormer variant to keep the implementation consistent between DAFormer, HRDA, and MIC. 

Best,
Lukas

**Comment by EEAIC** [comment]
Thank you for your reply. 👍
