### ISSUE TITLE
Can I train the model using target domain data without semantic segmentation annotations?

### ISSUE THREAD

**Issue by itsYunfei** [lhoyer/MIC#19]
Hello, @lhoyer 

I'm interested in using your model for my project, and I have a question regarding the training data. I have two datasets:

- Source domain: I have collected this dataset using the Carla simulator, and it comes with proper semantic segmentation annotations.
- Target domain: For this dataset, I do not have semantic segmentation annotations available.

Is it possible to train the model using this combination of datasets？

Please let me know if there are any workarounds or alternative approaches that I can consider to make use of the data I have. Your guidance would be much appreciated.

**Comment by lhoyer** [comment]
Hi @itsYunfei,

Yes, this is possible. The target domain annotations are never used during training and are just a legacy artifact as discussed in https://github.com/lhoyer/MIC/issues/11 and https://github.com/lhoyer/DAFormer/issues/34.
