### ISSUE TITLE
About the code implementation

### ISSUE THREAD

**Issue by kagawa588** [lhoyer/MIC#2]
Hi, authors

Thanks for your great recent work MIC in DA, I am interested in it.

I want to training the model myself, but met the below issue, could you pls help?

Traceback (most recent call last):
  File "/home/Desktop/MIC/seg/run_experiments.py", line 79, in <module>
    f.write(child_cfg.pretty_text)
AttributeError: 'dict' object has no attribute 'pretty_text'

Thanks

**Comment by lhoyer** [comment]
Thank you for your interest in our work. I pushed a fix. Please, let me know if you encounter further problems.

**Comment by TahereSaidi** [comment]
@kagawa588 Can you guide me how I can use my dataset?
I don't want to use it for object detection and I don't know what files to change in order to introduce my dataset?
