### ISSUE TITLE
Discussion: why does distribution shift (caused by the large ratio of masking) not affect the UDA?

### ISSUE THREAD

**Issue by KebinWu** [lhoyer/MIC#20]
This is a really nice work,  showing significant improvement with such a simple solution. 

I am thinking to apply the similar idea into other research topics such as semi-supervised learning, etc. However, I found that it actually brings negative effects to the performance, or at the very most no improvement at all. I was trying to figure out the reasons.  Here are my initial guess.

Unlike the MAE method, the masked blocks in MIC are also used in the training. Hence, the introduced masking brings distribution shift to the input and each layers thereafter: the labeled data and the unlabeled data will be under different distribution.  Even though it may make sense, I didn't get why such distribution shift is not an issue for the UDA tasks.  Could you please offer your idea about it? or the reason is just in another direction. 

Thank you.

**Comment by lhoyer** [comment]
I would hypothesize that learning context relations is more crucial in UDA than it is in single-domain learning. You can find some experimental analysis about this in HRDA Sec. 5.4 (https://arxiv.org/pdf/2204.13132.pdf) and in the video presentation of HRDA (https://youtu.be/z9OJdaJ0i24?t=75). This thought is also supported by Tab. 9 in the MIC paper showing that MIC only provides minor improvements in the fully-supervised setting. Therefore, I would expect that the effect of the improved context relations by MIC is more pronounced in UDA than in single-domain semi-supervised learning.

**Comment by KebinWu** [comment]
Thank you for the prompt reply.
That is a very reasonable explanation.
