### ISSUE TITLE
Is supervised loss L^s applied to both source and target data?

### ISSUE THREAD

**Issue by Hayoung93** [lhoyer/MIC#21]
Hi, I read your paper very interestingly and currently following your code implementation.

Unlike classification branch which doesn't use target domain's label information, it seems that the code of detection branch is using target domain's ground truth bboxes. Is it intentional or did I miss something?

Thank you.

The cls branch:
https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/cls/examples/cdan_mcc_sdat.py#L206-L207

At the det branch:
https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/det/maskrcnn_benchmark/engine/trainer.py#L137-L145

**Comment by krumo** [comment]
Hi, thanks for your interest! For domain adaptation detection, the target ground truth is loaded but not used in loss computation. Our strategy is to use a flag to filter out losses on target domain data when computing task losses on [RPN](https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/det/maskrcnn_benchmark/modeling/rpn/loss.py#L62) and [bbox head](https://github.com/lhoyer/MIC/blob/master/det/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L195). To avoid confusion, we also use a pseudo label to replace the annotations of target domain when [loading data](https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/det/maskrcnn_benchmark/data/datasets/coco.py#L76).

**Comment by Hayoung93** [comment]
Thanks for the explanation! :smiley:
