### ISSUE TITLE
(Detection, DAInsHead) Loop ends at the first step

### ISSUE THREAD

**Issue by Hayoung93** [lhoyer/MIC#22]
Hi, would you mind to help me about this code?

Inside the `inshead` for instances' domain classification, the loop spanning `levels` ends at the first step.
https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/det/maskrcnn_benchmark/modeling/da_heads/da_heads.py#L174-L191

It is different to `imghead` for images' domain classification which operates over all features from FPN, and I wonder if this is a bug.

Additionally, is `levels` indicates levels of FPN output?

Thank you!

**Comment by krumo** [comment]
Hi, thanks for your question. However, I don't agree that the loop ends at the first step. The `inshead` accepts instance-level features and the FPN levels as the input. As described in https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/det/maskrcnn_benchmark/modeling/poolers.py#L111, the instance-level features should be a tensor with the shape of `(num_rois, num_channels, output_size, output_size)`, which is different from the image-level features' shape `(num_scales, num_batches, num_channels, feat_height, feat_width)`. Thus, `inshead` processes the instance-level feature with a different way compared to `imghead`. 

And `levels` is the output of https://github.com/lhoyer/MIC/blob/1aa2f5ea6aed4b5601d5106464302255470b86af/det/maskrcnn_benchmark/modeling/poolers.py#L11. It should have a shape of `(num_rois, )` and it indicate the scale level each ROI feature belongs to. The mapping strategy follows the description in the original [FPN paper](https://arxiv.org/abs/1612.03144).

To make a summary, in my opinion, this `inshead` defines four instance-level discriminator for four scale levels in FPN respectively. For the input instance-level features, the loop would go though all scale levels and it uses `idx_in_level` to find the indexes of the instance-level features belonging to the current scale level. The selected instance-level features would then be fed to the instance-level discriminator of the same scale level.

Please let me know if you find my explanation solve your confusion.

**Comment by Hayoung93** [comment]
Thanks for detailed explanation. It really helped me understanding the code. However, in my opinion, it seems that the indent of `return`  should change. Would you mind to confirm this? Thank you!

**Comment by krumo** [comment]
Sorry for the late reply. Yes, you are right. We fixed this bug and re-ran the experiments obtaining 47.4 mAP. The difference to the reported performance (47.6 mAP) is negligible considering training noise. It shows that the bug has no significant effect on the performance. For this reason and in order to keep the implementation consistent with the paper and the SADA baseline, we will still keep the old implementation.

**Comment by Hayoung93** [comment]
Thanks for the confirmation and the great work :smiley:
