### ISSUE TITLE
Installation Instructions 

### ISSUE THREAD

**Issue by Bharat-Goyal** [lhoyer/MIC#23]
I noticed that there are some issues in the directory structure in the installation instructions (the module we need for convert_cityscapes_to_coco.py doesn't get installed correctly into cityscapesScripts).

**Comment by Bharat-Goyal** [comment]
#24 suggested the fix :) # #

**Comment by krumo** [comment]
Hi, thanks for your report and your example! Yes, you are right. The target path in the installation instruction contains a typo. This issue has been fixed in the latest commit.
