### ISSUE TITLE
How to run the source-only model?

### ISSUE THREAD

**Issue by XGGNet** [lhoyer/MIC#27]

**Comment by lhoyer** [comment]
The MIC repository does not support source-only training at the moment.

**Comment by Victory8858** [comment]
> The MIC repository does not support source-only training at the moment.

Training on a source-only dataset might not get a good result, right? I think MIC method is suitable for domain adaptive problems, am I right? Looking forward to your reply!

**Comment by lhoyer** [comment]
Training only on the source domain will naturally perform worse than utilizing UDA with additional unlabeled target images. You can find some reference results in the DAFormer paper https://arxiv.org/abs/2111.14887 in Tab. 1.

Yes, MIC is well suitable for domain adaptation as we have shown in the paper.
