### ISSUE TITLE
How many gpus do you use for seg tasks

### ISSUE THREAD

**Issue by jiangzhengkai** [lhoyer/MIC#3]
Thanks for your great work. I want to know how many gpus you use for training? It seems you use only one gpu for training.

**Comment by lhoyer** [comment]
Yes, we use use only one GPU across all experiments (including the segmentation task). In particular, we use a Titan RTX for MIC(HRDA) and an RTX 2080 Ti for MIC(DAFormer).

**Comment by jiangzhengkai** [comment]
Thanks for your quick reply, have you try using more gpus for faster training speed?

> Thanks for your interest in our work. Yes, we use use only one GPU across all experiments (including the segmentation task). In particular, we use a Titan RTX for MIC(HRDA) and an RTX 2080 Ti for MIC(DAFormer). These are the same GPUs as used in the original HRDA and DAFormer, respectively.

**Comment by jiangzhengkai** [comment]
@lhoyer Plus, would you mind provide ResNet-101 config?

**Comment by lhoyer** [comment]
The ResNet config is part of the experiment with ID 81. You can find more information how to use the experiment system in `seg/README.md`.
