### ISSUE TITLE
Validation dataset is same as test data?

### ISSUE THREAD

**Issue by toshi2k2** [lhoyer/MIC#39]
Hi, 

I noticed that the validation data appears to be same as the test data in image classification code.
`get_dataset` function (MIC/cls/examples/utils.py#L85). Is this correct?

**Comment by lhoyer** [comment]
Hi @toshi2k2,

This is intended. We follow previous works in this evaluation protocol: 
https://github.com/val-iisc/SDAT
https://github.com/thuml/Transfer-Learning-Library

Best,
Lukas

**Comment by lhoyer** [comment]
I agree that this is not ideal. However, we use this protocol to ensure comparability with previous UDA methods that use the same protocol. We have used these particular datasets as they are the common benchmarks for UDA in image classification.
