### ISSUE TITLE
About the result of gta->cityscapes

### ISSUE THREAD

**Issue by Mamduh-k** [lhoyer/MIC#4]
Hello author, I retrained mic according to your setting, but the result in gta->cityscapes was only 72.15, which was much lower than the one reported in your paper. The following is my training log：

[https://airportal.cn/469474/MMejPgx5t6](url)

**Comment by lhoyer** [comment]
Thank you for your interest in our work. It appears that you use different library versions than specified in `seg/requirements.txt`. This alters the behavior of the framework. Please, set up a new environment according to the instructions in `seg/README.md`. Before releasing the code, we have double-checked the reproducibility with three different random seeds and got 75.62, 76.03, 75.90 mIoU on GTA->Cityscapes.

**Comment by Mamduh-k** [comment]
Thanks for the author's answer, I would also like to know if the installation of MMCV-full is necessary, I only installed mmcv.

**Comment by lhoyer** [comment]
Please, use mmcv-full==1.3.7.

**Comment by lhoyer** [comment]
Have you been able to reproduce the results with the environment setup instructions from the readme?

**Comment by Mamduh-k** [comment]
No, I still can't replicate the results.

**Comment by lhoyer** [comment]
Could you please provide the log that I can have a look for possible reasons?

**Comment by lhoyer** [comment]
I have provided a simplified environment setup in https://github.com/lhoyer/MIC/issues/8#issuecomment-1383777610, which makes it easier to set up a reproducable environment. For further information, please refer to issues #8.
