### ISSUE TITLE
Whether it is fair to use FPN in the model?

### ISSUE THREAD

**Issue by Victory8858** [lhoyer/MIC#41]
Hi, thanks to your work! I want to ask whether it is fair to use FPN? Because previous works mostly used Faster R-CNN without FPN, how do you think of it, thank you very much!

**Comment by krumo** [comment]
Hi, thanks for your interests! I would assume your question is about the MIC for domain adaptive object detection part. 

The experiments of MIC for DA detection is to prove the generalization ability of MIC on various DA tasks. Thus, we pick a DA detection method(SADA[1]) published in recent years and combine it with MIC to see whether we can get further improvement. For the comparison, we present a system-level comparison with previous works with the same ResNet-50 backbone as different works utilize different architectures(Faster R-CNN, FCOS...) and different training strategies(data augmentation, training iterations, postprocessing...). Plus, some of the compared methods in the paper also utilize a FPN-based architecture like SIGMA[2]. I consider it rational to present a system-level comparison for DA detection in the paper.

For the usage of FPN in SADA, as SADA explores to perform cross-domain feature alignment in multi-scale, it develops some designs specifically on FPN and a fair comparison is presented in the original paper.

[1] Y. Chen, H. Wang, W. Li, C. Sakaridis, D. Dai, and L. V. Gool. Scale-aware domain adaptive faster r-cnn. IJCV.
[2] W. Li, X. Liu, and Y. Yuan. SIGMA: Semantic-complete Graph Matching for Domain Adaptive Object Detection. CVPR 2022
