### ISSUE TITLE
Question about reproducing DAFormer for Cityscapes-to-DarkZurich

### ISSUE THREAD

**Issue by SanghoonKim918** [lhoyer/MIC#44]
Hi, Thanks for your great work.
 
I attempted to reproduce your previous work(DAFormer) and achieved similar results for the GTA to Cityscapes and Synthia to Cityscapes tasks. However, I did not achieve the performance levels stated in the paper for the Cityscapes to DarkZurich (Test) and Cityscapes to ACDC (Test) tasks (mIoU=53.8, 55.4).

Regarding the implementation details, the only information I could find for DAFormer without MIC was the usage of half resolution. Therefore, I only made a change in the configuration file from '../base/datasets/uda_gta_to_cityscapes_512x512.py' to '../base/datasets/uda_cityscapes_to_darkzurich_512x512.py'. I wonder if there's anything I missed.

Here are the details of my environment:
```
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2+cu113
OpenCV: 4.4.0
MMCV: 1.4.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.16.0+81782e0
```

Here is the result (Cityscapes to DarkZurich (Test)):
```
IoU road            : 88.17
IoU sidewalk        : 48.98
IoU building        : 69.75
IoU wall            : 29.99
IoU fence           : 16.46
IoU pole            : 50.43
IoU traffic light   : 39.95
IoU traffic sign    : 39.59
IoU vegetation      : 54.96
IoU terrain         : 29.87
IoU sky             : 59.57
IoU person          : 53.39
IoU rider           : 53.64
IoU car             : 79.65
IoU truck           : 60.29
IoU bus             : 4.12
IoU train           : 89.25
IoU motorcycle      : 40.03
IoU bicycle         : 34.07
------------------------------------
Mean IoU over 19 classes: 49.59
```
Thank you once again for your excellent work.

**Comment by lhoyer** [comment]
Hi @SanghoonKim918,

Thank you for your interest in our work! Can you please share the config file of your training and the training log so that I can check both?

Best,
Lukas

**Comment by SanghoonKim918** [comment]
Hi, thanks for your quick reply.

Here are the config file and the training log of my training.
[230602_2159_cs2darkz_uda_daformer_mitb5_s0_a46c0.txt](https://github.com/lhoyer/MIC/files/11664459/230602_2159_cs2darkz_uda_daformer_mitb5_s0_a46c0.txt)
[20230602_220005.log](https://github.com/lhoyer/MIC/files/11664435/20230602_220005.log)

Thank you once again for your excellent work.

**Comment by lhoyer** [comment]
> 

Hi @SanghoonKim918,

Your config file looks good. You can find the original checkpoint, config, and log of DAFormer for Cityscapes-to-DarkZurich for comparison here: https://github.com/lhoyer/DAFormer#checkpoints

I noticed that your library versions (i.e. python, torch, torchvision, and mmcv) are different. This can change the behavior of the framework. I would recommend to follow the environment setup as described in the README.md.

**Comment by SanghoonKim918** [comment]
Thanks @lhoyer,

Maybe that's the only way I can do it. I will try and share the results.
