### ISSUE TITLE
Questions about distributed training

### ISSUE THREAD

**Issue by RyanQR** [lhoyer/MIC#46]
I noticed that your project only uses one GPU. Can your code be trained distributed?

**Comment by Victory8858** [comment]
I also have the same question, thank you!

**Comment by lhoyer** [comment]
We only trained MIC on a single GPU and did not use distributed training.

**Comment by kimkj38** [comment]
There's distributed option(args.launcher) in the tools/train.py line106.
But your code is not providing distributed training?

**Comment by EstrellaXyu** [comment]
> I noticed that your project only uses one GPU. Can your code be trained distributed?

I have the same problem. Have you solved this?
