### ISSUE TITLE
Questions about another domain adaption dataset work in segmentation

### ISSUE THREAD

**Issue by jetitime** [lhoyer/MIC#47]
Dear Author,
Thank you for your excellent work from DAFormer to HRDA and now MIC!

I want to use another domain adaption dataset with MIC seg task. I have get 3 json files for new dataset.
 I add exp <ID> in experiments.py.
[experiments.txt](https://github.com/lhoyer/MIC/files/11720517/experiments.txt)

And I created /MIC-master/seg/configs/_base_/datasets/uda_potsdam_to_isprs_1024x1024.py
[uda_potsdam_to_isprs_1024x1024.txt](https://github.com/lhoyer/MIC/files/11720556/uda_potsdam_to_isprs_1024x1024.txt)

It's really sad that something goes wrong and I don't know how to deal with it. Really hoping to get your advice. Thank you very much.

![Cache_-d76db09880ac065 (1)](https://github.com/lhoyer/MIC/assets/101321788/a3b0beb2-c5e4-4b16-a110-e3f68e49f618)

**Comment by lhoyer** [comment]
Hi @jetitime,

Thank you for your interest in our works! 

It seems that your code does not enter this code branch for the UDADataset https://github.com/lhoyer/MIC/blob/81782e070f5e9f1911c9eeaa0353129b4f073850/seg/mmseg/datasets/builder.py#L70 even though it should. I would suggest to run the code with a debugger to find out why this is the case.

Best,
Lukas

**Comment by jetitime** [comment]
Thank you very much! I'll try it.
