### ISSUE TITLE
Is there a mistake in Figure1?

### ISSUE THREAD

**Issue by xiaoachen98** [lhoyer/MIC#5]
Thanks for your impressive work!
I want to kindly remind you whether the stop-gradient mark should be put on the student branch rather than the teacher branch in Figure 1(c).
![1670553368155](https://user-images.githubusercontent.com/56393454/206611283-1971b376-350f-46b7-9cf2-61a93dee1ebb.png)

**Comment by lhoyer** [comment]
Thank you for your interest in our work! Yes, you are right, the stop gradient mark should be on the teacher / upper branch. We will fix it in the next arxiv version.
