### ISSUE TITLE
If I want to implement sim10k2cityscapes in det code, what do I do？

### ISSUE THREAD

**Issue by HDUyiming** [lhoyer/MIC#51]
Thank you for your excellent work！If I want to implement sim10k2cityscapes in det code，How do I get a label file that contains only the car？In addition, what are the requirements for sim10k label file？

**Comment by Victory8858** [comment]
You can add the dataset root in MIC-master/det/maskrcnn_benchmark/config/paths_catalog.py and modify the yamlfile, the annotations of sim10K can get from the offical website and you can write a code script to recreate the label of sim10k which only contains only car(coco or voc format are also OK)

**Comment by HDUyiming** [comment]
> You can add the dataset root in MIC-master/det/maskrcnn_benchmark/config/paths_catalog.py and modify the yamlfile, the annotations of sim10K can get from the offical website and you can write a code script to recreate the label of sim10k which only contains car(coco or voc format are also OK)
**Thanks for your answer,** I'll start by commenting out the other categories in `/home/cuiyiming/MIC/ det/tools/cityscapes convert_cityscapes_to_coco`, just keeping cars，Then convert the official label of sim10k into coco format. 
Is it possible to execute `/home/cuiyiming/mic-5-re2 /det/tools/test_net.py` directly？

**Comment by HDUyiming** [comment]
我已经测出来sim10k->cityscapes的mAP50有0.586了

**Comment by Victory8858** [comment]
请问有测kitti->cityscapes的mAP50吗，感觉这个数据集上性能表现一般

**Comment by HDUyiming** [comment]
> 请问有测kitti->cityscapes的mAP50吗，感觉这个数据集上性能表现一般

你好，我测试了kitti->cityscapes，性能只在48.5左右，确实不高，另外也测试了VOC->Clipart的但是性能也非常的差，只有25.0左右，考虑到MIC是用在SADA上的，SADA的K->C汇报结果是45.2，故48.5提高了三个点也很能说明MIC的有效性，但只能说这个性能对于目前主流的性能来说仍然是欠佳的，不过SADA在VOC->Clipart的汇报结果有43.3，我使用MIC（SADA）的代码中的SADA代码去跑也还是异常低只有22.3左右，复现不出来SADA中汇报的结果
