### ISSUE TITLE
RuntimeError: CUDA Out of memory

### ISSUE THREAD

**Issue by JCongLang** [lhoyer/MIC#56]
I run the code python on NVIDIA 4090 24G ：
`python run_experiments.py --exp 80`
But when training proceeds to the second validation（8000iters），it occour problem：`RuntimeError: CUDA Out of memory`。
and i set `interval=40`，it will occour on the 80th iteration。
Can you help me?
Wish for your reply, thank you!

**Comment by yuheyuan** [comment]
> I run the code python on NVIDIA 4090 24G ： `python run_experiments.py --exp 80` But when training proceeds to the second validation（8000iters），it occour problem：`RuntimeError: CUDA Out of memory`。 and i set `interval=40`，it will occour on the 80th iteration。 Can you help me? Wish for your reply, thank you!

have you solve the problem

**Comment by JCongLang** [comment]
> > I run the code python on NVIDIA 4090 24G ： `python run_experiments.py --exp 80` But when training proceeds to the second validation（8000iters），it occour problem：`RuntimeError: CUDA Out of memory`。 and i set `interval=40`，it will occour on the 80th iteration。 Can you help me? Wish for your reply, thank you!
> 
> have you solve the problem

no，i haven't.
Do you have any good ideas？

**Comment by lhoyer** [comment]
I personally did not observe this issue. Possibly, there are some cached tensors not freed properly. You could try the tips provided in https://pytorch.org/docs/stable/notes/cuda.html#environment-variables to address this issue.

**Comment by ricky-696** [comment]
@JCongLang Hello, I have same problem, did you solved this issue?
