### ISSUE TITLE
Submission Inquiry for ACDC Test Results

### ISSUE THREAD

**Issue by rayeh1063007** [lhoyer/MIC#57]
Hi, Thanks for your great work.

I have conducted experiments using your method and tested it on the ACDC test dataset. Could you please let me know where I should submit the test results for ACDC? I have registered on the ACDC website, but my registration has not been approved, and therefore I am unable to submit the results. Is there any alternative way to submit with the testing?

Thank you!

**Comment by lhoyer** [comment]
Hi @rayeh1063007,

There is no alternative way of obtaining the results on the test set. Alternatively, you could report the val set performance. To get it for DAFormer, HRDA, and MIC, you can have a look at the provided checkpoints+logs.
