### ISSUE TITLE
use check point for pre_train on custom dataset

### ISSUE THREAD

**Issue by TahereSaidi** [lhoyer/MIC#58]
Hello. I want to use your algorithm  But on my dataset. I want to use MIC for object detection. Also, I don't want to make the model from scratch and I  want to use the provided checkpoints to fine-tune . But I don't know how to do this.
Do I need to do the commands in [INSTALL.md]  for fine-tuning?
it will be favor to me to resolve my problem

**Comment by krumo** [comment]
Hi, sorry for the late reply. As the detection part is implemented based on [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark), I would suggest you follow their example like [e2e_faster_rcnn_R_101_FPN_1x_caffe2.yaml](https://github.com/facebookresearch/maskrcnn-benchmark/blob/main/configs/caffe2/e2e_faster_rcnn_R_101_FPN_1x_caffe2.yaml) to finetune a pretrained model on a dataset. Specifically, I believe you can specify the MODEL.WEIGHT to a path link to the provided checkpoints and start training on your custom data. For fine-tuning, you still have to follow the steps in [INSTALL.md] to configure the environment to run the code, but you don't have to run the Cityscapes-related commands.
