### ISSUE TITLE
Dead download links

### ISSUE THREAD

**Issue by FlorentF9** [lhoyer/MIC#59]
Hi,

The download links for OfficeHome and VisDA2017 are dead. I get following message : "Sorry, but the requested page could not be found.".
Also, when downloading OfficeHome from the official website, I don't get the required "image_list" directory, but a single "imagelist.txt" file, which prevents me from running the code.

Thanks for your help

**Comment by lhoyer** [comment]
This seems to be related to the following issue of the used Transfer-Learning-Library: https://github.com/thuml/Transfer-Learning-Library/issues/230.

**Comment by lhoyer** [comment]
For the moment, you can just split the imagelist.txt into image_list/Art.txt, image_list/Clipart.txt, and so on based on the corresponding directory names in the given file paths.

**Comment by LZ-CH** [comment]
Hi, 
Can you please re-release the image_list.zip of the office-home data set? I tried to divide it myself, but the format it requires seems to be inconsistent with the official image_list.txt format.
Thanks for your help

**Comment by LZ-CH** [comment]
Now, I can download it from https://cloud.tsinghua.edu.cn/f/1b0171a188944313b1f5/?dl=1.
