### ISSUE TITLE
How do I config MIC (DAFormer) ?

### ISSUE THREAD

**Issue by seabearlmx** [lhoyer/MIC#6]
Hi, I want to implement DAFormer with MIC, I should how to modify the config file.

**Comment by lhoyer** [comment]
The MIC(DAFormer) config is part of the experiment with ID 81 (see [experiments.py](https://github.com/lhoyer/MIC/blob/34dad1283c44e4cd269ce756e2b686d418d87c22/seg/experiments.py#L417)). You can find more information how to use the experiment system in [seg/README.md](https://github.com/lhoyer/MIC/tree/master/seg#training).

**Comment by seabearlmx** [comment]
Thanks for your reply!
