### ISSUE TITLE
Why Do Target Datasets Have ann_dir? 

### ISSUE THREAD

**Issue by Woochang4862** [lhoyer/MIC#64]
When I was looking for the UDA model, I watched your paper. My task is semantic segmentation, which makes ground truth from distorted images without labels. Then, I tried to transform your code gtaHR2csHR_mic_HRDA.py and related codes. While I changed the codes, I wondered why the target domain data has labels(annotations, gt) like ann_dir='gtFine/train'. Just as expected, when I ran my code in train mode, this error occurred. 
`
File "workdir\seg\mmseg\datasets\uda_dataset.py", line 166, in __getitem__
    s2 = self.target[idx % len(self.target)]
  File "workdir\seg\mmseg\datasets\custom.py", line 198, in __getitem__
    return self.prepare_train_img(idx)
  File "workdir\seg\mmseg\datasets\custom.py", line 212, in prepare_train_img
    ann_info = self.get_ann_info(idx)
  File "workdir\seg\mmseg\datasets\custom.py", line 174, in get_ann_info
    return self.img_infos[idx]['ann']
KeyError: 'ann'
`
I was impressed by your paper, and you and your results are my hope. So, I hope that you respond to my issue and that the unlabeled dataset doesn't support MIC.

**Comment by lhoyer** [comment]
This is a relict of the original dataset structure of the mmseg framework, which was designed for supervised training. The target ground truth is never used during UDA training as discussed in [#11](https://github.com/lhoyer/MIC/issues/11).

**Comment by Woochang4862** [comment]
Thanks a lot!
