### ISSUE TITLE
Pretrained model download problem

### ISSUE THREAD

**Issue by Jumponthemoon** [lhoyer/MIC#66]
Hi，

When i use the "sh sh tools/download_checkpoints.sh" for downloading the pretrained mit_b5.pth model, it throws error:
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1d7I50jVjtCddnhpf-lqj8-f13UyCzoW1 "

When i click the link it gave, the browser says i don't have the access to the file.

Can you help me solve it?

**Comment by ibanezfd** [comment]
Hi, I'm having the same issue. How did you solve it?

**Comment by kimkj38** [comment]
I got a same problem. How did you solve this?

**Comment by lhoyer** [comment]
Please, have a look at https://github.com/lhoyer/DAFormer/issues/74.

**Comment by kimkj38** [comment]
@lhoyer Thanks for your reply!
