### ISSUE TITLE
What is the respective file on SegFormer OneDrive for pretrained/mit_b5.pth

### ISSUE THREAD

**Issue by AlexTo** [lhoyer/MIC#68]
First of all, thanks a lot for the awesome work. I have a question, from other issues, I understand that I can download pretrained weights from SegFormer OneDrive [here](https://connecthkuhk-my.sharepoint.com/personal/xieenze_connect_hku_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fxieenze%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fsegformer%2Ftrained%5Fmodels)

However, which one is the weight for `pretrained/mit_b5.pth` ? I can see 2 files 

<img width="353" alt="image" src="https://github.com/lhoyer/MIC/assets/296212/fc0382ae-89d4-4fad-b487-1c4c93b0e958">

I guess I should pick the one pretrained on ADE because it doesn't make sense to pick the one pretrained on Cityscapes?

Best,

**Comment by lhoyer** [comment]
Neither of those. This one is the correct onedrive link for the ImageNet pre-trained weights: https://connecthkuhk-my.sharepoint.com/personal/xieenze_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fxieenze%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fsegformer%2Fpretrained%5Fmodels&ga=1

**Comment by AlexTo** [comment]
@lhoyer thanks a lot for your prompt reply but I think the link is no longer valid?

**Comment by lhoyer** [comment]
You can find the link in this section of the segformer readme: https://github.com/NVlabs/SegFormer#training

**Comment by AlexTo** [comment]
Yup I got it, thanks a lot
