### ISSUE TITLE
About the test process

### ISSUE THREAD

**Issue by JunkunPeng17** [lhoyer/MIC#7]
Hi, Thanks for your great work and share the codes.I met a problem when I finished the training and wanted to do an evaluation. I followed the guideline but I got a bug:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6admysin/tmpjdmakb9n.json'.
To be specifical, I reproduced in the seg task.

**Comment by lhoyer** [comment]
Thank you for your interest in our work. 

The path to your config is not the default one. Have you intentionally changed it? Have you checked the content of the log folder? Does it help if you change line 11 in test.sh to `CONFIG_FILE="${TEST_ROOT}/*${TEST_ROOT: -1}.py" (.py file ending)?

**Comment by lhoyer** [comment]
You're welcome. I changed the config files from .json to .py but I forgot to change it in test.sh as well. I just pushed the fix discussed above.
