### ISSUE TITLE
Does this code really work in the way of Unsupervised?

### ISSUE THREAD

**Issue by behnaz-sadeghigol** [lhoyer/MIC#83]
Does this code really work in the way of Unsupervised?
In the det/maskrcnn_benchmark/config/paths_catalog.py file, if we leave the "ann_file" data from "cityscapes_fine_instanceonly_seg_train_cocostyle" empty, there is an error, and if we give it random, it gives zero accuracy. Does this method really work Unsupervised?

**Comment by krumo** [comment]
Hi, thanks for your interest! This work focuses on classical unsupervised domain adaptation setting, which assumes we can access to a **labeled** source dataset and **unlabeled** target dataset during training. In your example, we treat Cityscapes as source dataset and foggy Cityscapes as target dataset. Thus, a correctly annotated cityscapes_fine_instanceonly_seg_train_cocostyle" is necessary for this case. You can try assigning a random annotation for "foggy_cityscapes_fine_instanceonly_seg_train_cocostyle" to see whether it works.
